name: roughpage_preview
on: workflow_dispatch
jobs: 
  roughpage_preview:
    runs-on: windows-latest
    steps:
      - name: clone repository
        run: git clone https://github.com/Disat/roughpage.git
      - name: debug list
        run: ls
      - name: cd  (Set-Location) 
        run: Set-Location roughpage
      - name: debug list
        run:  ls
      - name: install roughpage
        run: go mod tidy
      - name: build roughpage
        run: go build .
      - name: execute roughpage
        run: .\roughpage.exe
