name: roughpage_preview
on: workflow_dispatch
jobs: 
  roughpage_preview:
    runs-on: windows-latest
    steps:
      - name: download releases
        uses: i3h/download-release-asset@v1
        with:
          owner: Disat
          repo: roughpage
          tag: latest
          file: roughpage.exe
          path: ./
