name: roughpage_preview
env:
  VERCEL_ORG_ID: ${{ secrets.ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.PROJECT_ID }}
on:
  push:
    paths:
     - 'markdown/**'
  workflow_dispatch:
jobs:
  roughpage_preview:
    runs-on: windows-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: download releases
        uses: i3h/download-release-asset@v1
        with:
          owner: Disat
          repo: roughpage
          tag: latest
          file: roughpage.exe
          path: ./
      - name: generate public directory
        run: .\roughpage.exe
      - name: Install Vercel CLI
        run: npm i  vercel@latest
      - name: deploy
        run: .\node_modules\.bin\vercel --prod -y
