name: roughpage_preview
on: workflow_dispatch
jobs: 
  roughpage_preview:
    runs-on: windows-latest
    steps:
      - name: download releases
        uses: robinraju/release-downloader@v1.8
        with:
            latest: true
            fileName: "roughpage.exe"
      - name: Display structure of downloaded files
        run: ls 
