name: roughpage_preview
env:
  VERCEL_ORG_ID: ${{ secrets.ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.PROJECT_ID }}
on: workflow_dispatch
jobs: 
  roughpage_preview:
    runs-on: windows-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: download releases
        uses: i3h/download-release-asset@v1
        with:
          owner: Disat
          repo: roughpage
          tag: latest
          file: roughpage.exe
          path: ./
      - name: debug list
        run: ls
      - name: generate public static direcory public
        run: .\roughpage.exe
      - name: debug list
        run: ls
      - name: Install Vercel CLI
        run: yarn global add vercel@canary
      - name: Add to Paths
        run: export PATH="$(yarn global bin):$PATH"
      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}
      - name: Build Project Artifacts
        run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}
      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}
