name: roughpage_preview
on: workflow_dispatch
jobs: 
  roughpage_preview:
    runs-on: windows-latest
    steps:
    - uses: actions/download-artifact@v4
    - name: Display structure of downloaded files
      run: ls 
